
services:
  backend:
    build: ./backend
    ports:
      - "3003:3000"

  frontend:
    build: ./frontend
    ports:
      - "8180:80"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_db
    ports:
      - "5438:5432"

  adminer:
    image: adminer
    ports:
      - "8081:8080"

  vscodium:
    image: lscr.io/linuxserver/vscodium:latest
    cap_add:
      - IPC_LOCK
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./vscode:/config
      - ./:/source
    ports:
      - 3800:3000
      - 3001:3001
    shm_size: "1gb"
